baseURL = 'http://nand2mario.github.io/'
languageCode = 'en-us'
title = 'Small things retro'
theme = 'Mainroad'
pagination.pagerSize = "10"

[services.disqus]
  shortname = "nand2mario-github-io"

[services.googleAnalytics]
  ID = 'G-HPP04YGFN2'

[Params]
  description = "Writings about FPGA for retro gaming and computing, and others." 
  twitter_cards = true
  readmore = true
  pager = true
  font_size = "l"
  post_meta = ["author", "date", "categories"] # Order of post meta information
#  authorbox = true
#  mainSections = ["blog", "about"]

[Params.Author]
  name = "nand2mario"
  bio = "Yours truly. Here to write about FPGA retro gaming and computing."
  avatar = "img/n2m.jpg"

[Params.logo]
  title = "Small things retro"

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  twitter = "nand2mario"
  github = "nand2mario"

# Support image attributes
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Guides'
    pageRef = '/guides'
    weight = 20